- hosts: all

  tasks:
    - name: Transfer the weedfs script
      copy: src=runfsserver.sh dest=/tmp/ mode=0777

    - name: Create file for volume server logs
      ansible.builtin.file:
        path: /tmp/fsvolumerun.logs
        state: touch

    - name: Install seaweedfs and start volume server
      ansible.builtin.shell: nohup /tmp/runfsserver.sh {{index . 0}} {{index . 1}} </dev/null >/tmp/fsvolumerun.logs 2>&1 &
      become: true